# Generated by Django 4.2.9 on 2024-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appBelajar", "0003_answers_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="image_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
