# Generated by Django 4.2.9 on 2024-03-16 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appBelajar", "0005_answers_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
